### ISSUE TITLE
Stereo image registration using GPU

### ISSUE THREAD

**Issue by furushchev** [ros-perception/image_pipeline#234] opened 2016-11-10 14:00 UTC
Since OpenCV 3 supports stereo image registration using GPU device, I'd like to let `stereo_image_proc` use GPU for further performance.
When providing via `apt` package, it needs runtime condition that check if CUDA is enabled and switch the methods.
Is there any ideas to achieve this feature?

**Comment by vrabaud** [comment] 2016-11-19 21:44
Duplicate of https://github.com/ros-gbp/opencv3-release/issues/5
You would need your own OpenCV I believe.

**Closed as completed by vrabaud** 2016-11-19 21:44 UTC
Labels: duplicate
