### ISSUE TITLE
video_recorder skips frames even when they arrive just a fraction too early

### ISSUE THREAD

**Issue by cbteeple** [ros-perception/image_pipeline#604] opened 2020-09-29 16:27 UTC
### Package
**image_view**

### Feature
_video_recorder_ skips frames when they arrive too soon to ensure proper framerate

### Expected Behavior
If a camera stream is running at 30 fps, then _video_recorder_ should be able to save a 30fps video without dropping frames

### Actual Behavior
_video_recorder_ skips frames when they arrive even a fraction of time too early. Since the opencv VideoWriter class expects frames to be given at the set framerate, we end up with a shorter video that plays back faster.

**Comment by mikeferguson** [comment] 2024-01-19 23:43
Calling this a duplicate of https://github.com/ros-perception/image_pipeline/issues/274 - at some point sec_per_frame needs a refactor

**Closed as completed by mikeferguson** 2024-01-19 23:43 UTC
