### ISSUE TITLE
ROS Buildfarm complains about std::shared_ptr

### ISSUE THREAD

**Issue by miquelmassot** [ros-perception/image_pipeline#305] opened 2017-11-09 08:51 UTC
In a package we have released, [srv_tools](https://github.com/srv/srv_tools), buildfarm complains in:
```
/opt/ros/kinetic/include/image_geometry/pinhole_camera_model.h:273:8: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   std::shared_ptr<Cache> cache_; // Holds cached data for internal use
        ^
```

**Comment by mikaelarguedas** [comment] 2017-11-09 16:19
Thnks  @miquelmassot for reporting this.

However tt looks like the problem is in the `image_geometry` package that is located on [another repository](https://github.com/ros-perception/vision_opencv).

See https://github.com/ros-perception/vision_opencv/pull/188 for the corresponding fix.

**Comment by vrabaud** [comment] 2017-11-11 16:42
Fixed in https://github.com/ros-perception/vision_opencv/pull/188

**Closed as completed by vrabaud** 2017-11-11 16:42 UTC
