### ISSUE TITLE
GLib-GObject-WARNING 

### ISSUE THREAD

**Issue by carmit** [ros-perception/image_pipeline#98] opened 2014-09-01 12:30 UTC
I get the following error:
(image_view:43558): GLib-GObject-WARNING **: invalid uninstantiatable type '<invalid>' in cast to 'GtkWindow'.

what is this type <invalid>? 

thanks.

**Comment by vrabaud** [comment] 2014-09-06 15:28
duplicate of #83 
Please continue the conversation there: which distro do you use ?

**Closed as completed by vrabaud** 2014-09-06 15:28 UTC
Labels: duplicate
