### ISSUE TITLE
Camera calibration crashes 

### ISSUE THREAD

**Issue by andres-ss25** [ros-perception/image_pipeline#43] opened 2013-10-09 15:58 UTC
Hi Comunity 

I try to calibrate the kinect with camera_calibration on ros-hydro. 

I type this command

$ rosrun camera_calibration cameracalibrator.py image:=/camera/rgb/image_raw camera:=/camera/rgb --size 8x6 --square 0.025

The cameracalibrator.py  show an error when running, sometimes during start, sometimes when the checkboard is moving in the frame. If the checkboard is in the middle of the frame when the aplication starts, then sometimes I can see the checkboard from the GUI and the aplication gets the first calibration data and then fails. 

The error message show:

OpenCV Error: Assertion failed (blockSize % 2 == 1 && blockSize > 1) in adaptiveThreshold, file /tmp/buildd/ros-hydro-opencv2-2.4.6-1precise-20130919-0139/modules/imgproc/src/thresh.cpp, line 797
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/ros/hydro/lib/camera_calibration/cameracalibrator.py", line 68, in run
    self.function(m)
  File "/opt/ros/hydro/lib/camera_calibration/cameracalibrator.py", line 134, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 740, in handle_msg
    scrib_mono, corners, downsampled_corners, board, (x_scale, y_scale) = self.downsample_and_detect(gray)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 410, in downsample_and_detect
    (ok, downsampled_corners, board) = self.get_corners(scrib, refine = True)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 378, in get_corners
    (ok, corners) = _get_corners(img, b, refine)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 156, in _get_corners
    (ok, corners) = cv.FindChessboardCorners(mono, (board.n_cols, board.n_rows), cv.CV_CALIB_CB_ADAPTIVE_THRESH | cv.CV_CALIB_CB_NORMALIZE_IMAGE | cv2.CALIB_CB_FAST_CHECK)
error: blockSize % 2 == 1 && blockSize > 1

I have installed Ubuntu 12.04 32 bit and ros-hydro.

Please, help me find a solution to this problem . Thanks very much

![captura de pantalla de 2013-10-09 10 52 29](https://f.cloud.github.com/assets/5648275/1298972/df2bc5d8-30fa-11e3-917f-aa1c51660836.png)

**Comment by BastiAB** [comment] 2013-10-14 08:45
I have exactly the same Problem. I'm using Ubuntu 12.04 and Ros-Hydro too. I also tried to use an asymmetric circle-pattern, but there I'vo got errors too. Using the cpp-code from the OpenCV-tutorial doesn't work either.
Does anyone know why this package doesn't work?

**Comment by vrabaud** [comment] 2013-10-14 08:50
it seems really weird. If you want to help, create a .rosinstall file with camera_calibration and opencv2 in debug mode and figure out why OpenCV is crashing.
I checked the OpenCV code and I don't see why it's crashing there.
@Biersack  , I guess you are on 32 bit, it is a very important detail
The code works for me on 64 bit and I spent yesterday trying to nail it:
- cross-compiled in 32 bit but could not run the code (I'm not an expert in cross-compilation)
- chroot 32 bit with Hydro on Raring. Things ran
- converted an old laptop to 32 bit Quantal. Things ran.
- downgrading my old laptop to Precise and we'll see ...
  Help is very welcome here.

**Comment by vrabaud** [comment] 2013-10-14 09:01
ok, I tried a Kinect with Hydro on a 32 bit Precise. Things ran.

All I can see if that you have a conflicting OpenCV on your machine. Do you have some opencv in /usr/local ?

If you do:
sudo updatedb
locate libopencv_core.so

What do you get ?

**Comment by BastiAB** [comment] 2013-10-14 09:31
Yeah, sorry, I forgot. I'm running on 32 bit. Following your Instructions vrabaud, I got this output:
+++++++++++++++++++++++++++++
locate libopencv_core.so
/opt/ros/hydro/lib/libopencv_core.so
/opt/ros/hydro/lib/libopencv_core.so.2.4
/opt/ros/hydro/lib/libopencv_core.so.2.4.6
/usr/lib/libopencv_core.so.2.3
/usr/lib/libopencv_core.so.2.3.1
++++++++++++++++++++++++++++++++++++++

**Comment by vrabaud** [comment] 2013-10-14 10:13
ok guys, I cannot reproduce that bug so if you want to debug, you'll have to help me. You need to:

```
sudo apt-get install python-rosdep python-rosinstall-generator python-wstool build-essential
```

Then:

```
rosinstall_generator camera_calibration opencv2 --rosdistro hydro  > hydro.rosinstall
wstool init -j8 src hydro.rosinstall
./src/catkin/bin/catkin_make_isolated --install --merge --cmake-args "-DCMAKE_BUILD_TYPE=Debug"
```

Source the setup.sh and then run your camera_calibration command and that should do it.
(light version of http://wiki.ros.org/hydro/Installation/Source)

**Comment by andres-ss25** [comment] 2013-10-15 14:51
Hello

I commented that solved the problem this weekend installing ubuntu 12.04 64
bits

2013/10/14 Biersack notifications@github.com

> I have exactly the same Problem. I'm using Ubuntu 12.04 and Ros-Hydro too.
> I also tried to use an asymmetric circle-pattern, but there I'vo got errors
> too. Using the cpp-code from the OpenCV-tutorial doesn't work either.
> Does anyone know why this package doesn't work?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-perception/image_pipeline/issues/43#issuecomment-26242676
> .

## 

*Cordialmente

Andrés Felipe Suárez S.
Ingeniero Electrónico.
Universidad del Valle
Cel: 313 625 52 32*

**Comment by vrabaud** [comment] 2013-10-16 08:25
Well, that is good but that does not explain the error :) can anybody compile OpenCV according to my instructions and test it ? Thx

**Comment by BastiAB** [comment] 2013-10-16 14:09
I tried to follow your instructions. But when I try to execute the last line of your proposal,

./src/catkin/bin/catkin_make_isolated --install --merge --cmake-args "-DCMAKE_BUILD_TYPE=Debug"
I'm getting an error that tells me that there is no such file or directory. What do I do wrong?

**Comment by vrabaud** [comment] 2013-10-16 15:03
Right, after sourcing your /opt/ros/hydro/setup.sh, it should be

```
catkin_make_isolated --install --merge --cmake-args "-DCMAKE_BUILD_TYPE=Debug"
```

And you source the setup.sh in install_isolated

**Comment by andres-ss25** [comment] 2013-10-16 19:32
Hi

I followed the instruction given by you. Affirmatively, it compiled and created three folder in my workspace. 1) build_isoleted 2) devel_isolated 3) install_isolated.

I try to run the node of calibration from install_isolated folder and the same error keeps happening. Mr maintenance can help me, I'm doing wrong?

**Comment by vrabaud** [comment] 2013-10-17 06:18
If the same error happens, great !!! That was not the case for me.
Now you can debug it. I hope you have some notion of debugging ....
Just gdb it and look through the OpenCV code to see the value of blockSize
Go to install_isolated/lib/camera_calibration and do:

```
gdb --args python cameracalibrator.py image:=/camera/rgb/image_raw camera:=/camera/rgb --size 8x6 --square 0.025
```

Then r and enter and that should run until it crashes.
Then p blockSize will give you the value when it crashes.
That would be a great start for me !

**Comment by BastiAB** [comment] 2013-10-18 11:36
I think the problem should have something to do with the functions for chessboard recognition. When I use an asymmetric circle grid instead of a chessboard the calibration window appears and the program starts to collect data for the calibration. But with this grid I got some errosr too, before the calibration comes to an end. The Error looks like that:

python: /build/buildd/cairo-1.10.2/src/cairo-surface.c:1287: cairo_surface_set_device_offset: Assertion `status == CAIRO_STATUS_SUCCESS' failed.

I don't know if all the errors we collected over the last days lead to one problem.

**Comment by vrabaud** [comment] 2013-10-20 10:45
ok, I've spent all of yesterday on it and here is what I've found so far:
- I managed to reproduce the crash by using an Ubuntu 32 bit Precise on a USB key (yay ! ...)
- I compiled things in RelWithDebInfo and found that the block_size computation in cvFindChessboardCorners around line 337 can fail and return -2147483641
- now, this is due to the function lrint that sometimes returns the above when called with lrint(96) ...... (lrint is called when using gcc in the function cvRound)
- using libcalib3d.so independently (Without ROS, in pure OpenCV code) seems to work on the same data (it never crashes at least)
- I cannot see any leak happening when the code crashes (memcheck with all options)

**Comment by vrabaud** [comment] 2013-10-20 22:09
ok, I was not able to reproduce it when compiling locally ... And replacing libopencv_imgproc with the compiled one fixed the issue (hence the error is probably in there, not in calib3d).
Then again, I could never reproduce the error in pure OpenCV code ... So maybe some weird interaction with nodelets ...
Anyway, I changed some compile flags and it works for me now. Please try 2.4.6-3 on hydro and 2.4.6-1 on groovy (they will be in shadow-fixed in 12 hours).

**Comment by BastiAB** [comment] 2013-10-21 10:50
Thank you very mutch for your work. Are these two new versions upgrades from the ros-opencv-package or from the standalone version of opencv?

**Comment by vrabaud** [comment] 2013-10-21 11:03
Yes, standard ros-opencv package. They built but are not in shadow-fixed yet (the rest of the dependents need to finish). You can still grab them from here though:
http://50.28.27.175/repos/building/pool/main/r/ros-hydro-opencv2/

**Comment by BastiAB** [comment] 2013-10-21 12:59
Ahh ok. Could you please explain to me the steps i need to do to replace the old ros-cv with your new one?

**Comment by vrabaud** [comment] 2013-10-21 13:34
download the .deb file for you and then "sudo dpkg -i *deb"

**Comment by BastiAB** [comment] 2013-10-22 07:31
Thank you very much. Awesome. There are no more errors when I'm using the calibration for a single webcam. Works fine. 
But the error described in #46 still appearswhen using the stereocalibration_node

**Comment by vrabaud** [comment] 2013-10-23 08:31
@andres-ss25  , can you please confirm that it works for you too ? Thx

**Comment by andres-ss25** [comment] 2013-10-23 18:45
Hi comunity
I have not tasted the solution that has been raised, I confirm this weekend

**Comment by vrabaud** [comment] 2013-11-02 14:17
ok, that seems fixed, please re-open if that's not the case.

**Closed as completed by vrabaud** 2013-11-02 14:17 UTC

**Comment by andres-ss25** [comment] 2013-11-02 15:23
Hello community, I inform that the proposed solution worked for me.

Mr Vrabaud thank you very much for the cooperation and dedication to make this case successfully resolved.  I send you good energy, thanks.

**Comment by vrabaud** [comment] 2013-11-02 18:43
@andres-ss25  , glad to hear ! Thank you for your kind words, that helps me replenish my motivation batteries :)
