### ISSUE TITLE
ROS Camera Calibration for Webcam - Not working

### ISSUE THREAD

**Issue by diwamanic** [ros-perception/image_pipeline#694] opened 2021-08-23 05:23 UTC
Hi peeps! As a part of learning, I am trying to perform Camera calibration with my laptop's Webcam. I am really new to this process. I will explain everything about how far I have come so far, and where I have issues in coming to an successful calibration.

My system specifications: Ubuntu 18.04, ROS Melodic.

For Camera streaming, I am using usb_cam ros package http://wiki.ros.org/usb_cam. And it is working perfectly fine.

After I launch the usb_cam-test.launch, I looked into the rostopic list, where I could find the following two topics: /usb_cam/image_raw /usb_cam/camera_info

So, I progressed forward to perform the camera calibration with the ros package "camera_calibration", but instead of getting a camera stream with calibration options as given in the tutorials, I get a black screen like below:

https://user-images.githubusercontent...

This calibration task is crucial to perform a task at my work. So, I would really need to get some help from someone who has been through this issue before. Thank you very much for the help

**Comment by JWhitleyWork** [comment] 2021-08-23 18:18
Closing as duplicate of #695.

**Closed as completed by JWhitleyWork** 2021-08-23 18:18 UTC
