### ISSUE TITLE
Compilation fails on OSX 10.10

### ISSUE THREAD

**Issue by rcodddow** [ros-perception/image_pipeline#107] opened 2014-10-28 21:39 UTC
```
==> Processing catkin package: 'depth_image_proc'
==> Building with env: '/Users/robert/ros_catkin_ws/install_isolated/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/Users/robert/ros_catkin_ws/build_isolated/depth_image_proc'
==> make -j8 -l8 in '/Users/robert/ros_catkin_ws/build_isolated/depth_image_proc'
[ 16%] [ 33%] [ 50%] Building CXX object CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyzi.cpp.o
Building CXX object CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyzrgb.cpp.o
Building CXX object CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyz.cpp.o
In file included from In file included from /Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzi.cpp::4747:
:
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h::286286::7676::  errorerror: : templatetemplate  argumentargument  forfor  templatetemplate  templatetemplate  parameterparameter  mustmust  bebe  a
a      
class       classtemplate template

    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                           ^
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                           ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:286:98: error: member initializer/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h :'PointCloud2IteratorBase'286 :does98 :not  name
error      : a non-staticmember  datainitializer  member'PointCloud2IteratorBase'  ordoes  basenot  classname

      a non-static data member or base class
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:297:94: /Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:error297: :94:template  argument errorfor:  template templatetemplate  parameterargument  mustfor  betemplate  atemplate
       parameterclass  musttemplate be
 a
      class template
    PointCloud2IteratorBase<T, const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, ...
    PointCloud2IteratorBase<T, const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, ...
                                                                                             ^
                                                                                             ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:297/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h::121297:: 121: error: error: member initializermember  initializer'PointCloud2IteratorBase'  'PointCloud2IteratorBase'does  doesnot  notname name

            aa  non-staticnon-static  datadata  membermember  oror  basebase  classclass

  ...const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ...const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}

                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzi.cpp:283:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:292:43:   sensor_msgs::PointCloud2Iterator<float> iter_y(*cloud_msg, "y");error
:                                           ^      ~~~~~~~~~~~~~~~
no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_y(*cloud_msg, "y");
                                          ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7:/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h :note: candidate constructor282 (the implicit default constructor): 7not: 
      viable:note : requires candidate0  constructorarguments,  (the implicit default constructor)but  not2
       wereviable:  requiresprovided 0
 arguments, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: : candidate constructor note: (the implicit copy constructor)candidate  notconstructor
       viable:(the implicit copy constructor)  requiresnot 
1       viable:argument,  requiresbut  12  argument,were  butprovided 
2 were provided
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzi.cpp:284:43/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:: 293:43error::  noerror:  matching noconstructor  matchingfor  constructorinitialization  forof 
initialization       'sensor_msgs::PointCloud2Iterator<float>'of

      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_z(*cloud_msg, "z");
                                          ^      ~~~~~~~~~~~~~~~  sensor_msgs::PointCloud2Iterator<float> iter_z(*cloud_msg, "z");

                                          ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: :7: note: candidatecandidate  constructorconstructor (the implicit default constructor)  (the implicit default constructor)not not

            viable:viable:  requiresrequires 0  0arguments,  arguments,but  but2  2were  wereprovided provided

class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor)class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator> 
not
            ^viable:
 requires 1 argument, but 2 were /Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.hprovided:282
:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzi.cpp:285:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_i(*cloud_msg, "intensity");
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:                                          ^      ~~~~~~~~~~~~~~~~~~~~~~~295
:45: error: no matching constructor/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h :for282 :initialization7 :of 
      note'sensor_msgs::PointCloud2Iterator<uint8_t>': 
candidate constructor (the implicit default constructor) not
      viable: requires 0 arguments, but 2 were provided
  sensor_msgs::PointCloud2Iterator<uint8_t> iter_g(*cloud_msg, "g");
                                            ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: noteclass PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>: 
candidate      ^ 
constructor (the implicit default constructor) not
      viable: requires 0 /Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.harguments,: 282but: 72:  were providednote: 
candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:296:45: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<uint8_t>'
  sensor_msgs::PointCloud2Iterator<uint8_t> iter_b(*cloud_msg, "b");
                                            ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not
      viable: requires 0 arguments, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:297:45: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<uint8_t>'
  sensor_msgs::PointCloud2Iterator<uint8_t> iter_a(*cloud_msg, "a");
                                            ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not
      viable: requires 0 arguments, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
In file included from /Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:42:
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:286:76: error: template argument for template template parameter must be a
      class template
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                           ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:286:98: error: member initializer 'PointCloud2IteratorBase' does not name
      a non-static data member or base class
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:297:94: error: template argument for template template parameter must be a
      class template
    PointCloud2IteratorBase<T, const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, ...
                                                                                             ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:297:121: error: member initializer 'PointCloud2IteratorBase' does not name
      a non-static data member or base class
  ...const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:152:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_y(*cloud_msg, "y");
                                          ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not
      viable: requires 0 arguments, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
/Users/robert/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:153:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_z(*cloud_msg, "z");
                                          ^      ~~~~~~~~~~~~~~~
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not
      viable: requires 0 arguments, but 2 were provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/Users/robert/ros_catkin_ws/install_isolated/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not
      viable: requires 1 argument, but 2 were provided
7 errors generated.
9 errors generated.
make[2]: *** [CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyzrgb.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyzi.cpp.o] Error 1
6 errors generated.
make[2]: *** [CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyz.cpp.o] Error 1
make[1]: *** [CMakeFiles/depth_image_proc.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'depth_image_proc': 
  Command '/Users/robert/ros_catkin_ws/install_isolated/env.sh make -j8 -l8' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/robert/ros_catkin_ws/build_isolated/depth_image_proc && /Users/robert/ros_catkin_ws/install_isolated/env.sh make -j8 -l8

Command failed, exiting.
```

**Comment by jmtatsch** [comment] 2014-11-03 17:02
Yupp, have the same issue here.
@jensenb
as template and clang specialist, can you give a hint?

**Comment by vrabaud** [comment] 2014-11-03 17:12
ok, I guess the code is not compatible with clang (or the other way around). What version are you using ? Thx.

**Comment by jmtatsch** [comment] 2014-11-03 17:31
-- The C compiler identification is AppleClang 6.0.0.6000054
-- The CXX compiler identification is AppleClang 6.0.0.6000054

**Comment by vrabaud** [comment] 2014-11-03 18:30
This message is actually unreadable: any way you can just compile it with j1 to avoid overlap of logs, thx.

**Comment by jmtatsch** [comment] 2014-11-03 18:49
Sorry, I thought you wanted to know which compiler is being used. The version of the code is 1.12.11.

With -j1 the log looks like this:

==> Processing catkin package: 'depth_image_proc'
==> Building with env: '/opt/ros/indigo/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/Users/tatsch/ros_catkin_ws/build_isolated/depth_image_proc'
==> make -j1 in '/Users/tatsch/ros_catkin_ws/build_isolated/depth_image_proc'
[ 16%] Building CXX object CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyz.cpp.o
In file included from /Users/tatsch/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:42:
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:286:76: error: template argument for template template parameter must be a class template
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                           ^
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:286:98: error: member initializer 'PointCloud2IteratorBase' does not name a non-static data member or base class
    PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:297:94: error: template argument for template template parameter must be a class template
    PointCloud2IteratorBase<T, const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                             ^
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:297:121: error: member initializer 'PointCloud2IteratorBase' does not name a non-static data member or base class
    PointCloud2IteratorBase<T, const T, const unsigned char, const sensor_msgs::PointCloud2, PointCloud2ConstIterator>::PointCloud2IteratorBase(cloud_msg, field_name) {}
                                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/tatsch/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:152:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_y(_cloud_msg, "y");
                                          ^      ~~~~~~~~~~~~~~~
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were
      provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were
      provided
/Users/tatsch/ros_catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:153:43: error: no matching constructor for initialization of
      'sensor_msgs::PointCloud2Iterator<float>'
  sensor_msgs::PointCloud2Iterator<float> iter_z(_cloud_msg, "z");
                                          ^      ~~~~~~~~~~~~~~~
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were
      provided
class PointCloud2Iterator : public PointCloud2IteratorBase<T, T, unsigned char, sensor_msgs::PointCloud2, PointCloud2Iterator>
      ^
/opt/ros/indigo/include/sensor_msgs/point_cloud2_iterator.h:282:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were
      provided
6 errors generated.
make[2]: **\* [CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyz.cpp.o] Error 1
make[1]: **\* [CMakeFiles/depth_image_proc.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'depth_image_proc': 
  Command '/opt/ros/indigo/env.sh make -j1' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/tatsch/ros_catkin_ws/build_isolated/depth_image_proc && /opt/ros/indigo/env.sh make -j1

Command failed, exiting.

**Comment by jmtatsch** [comment] 2014-11-04 11:05
Somehow clang had trouble with the namespaces, here a simple fix:
https://github.com/ros/common_msgs/pull/48

**Comment by vrabaud** [comment] 2014-11-05 06:29
Hi, I'll close this one as the bugfix got released upstream. Pleas re-open if that does not work.
Thx @jmtatsch for the fix !

**Closed as completed by vrabaud** 2014-11-05 06:29 UTC
