### ISSUE TITLE
Camera calibration causes spinning beachball on OSX

### ISSUE THREAD

**Issue by kubark42** [ros-perception/image_pipeline#72] opened 2014-05-22 01:14 UTC
When I try to use the calibration routine, it seems to function normally, only I get a spinning beachball in the place of my cursor. The upshot is that it's impossible to interact with the GUI.

On the backend, everything seems to be normal. The console updates with new calibration data, and the X, Y, Size, and Skew progress bars behave normally.

http://stackoverflow.com/questions/23642674/how-to-spawn-thread-and-initialize-qt-application-in-python-with-mac-osx is the only reference I've found to a python/OSX beachball problem, but I'm unsure if it applies here.

**Comment by vrabaud** [comment] 2014-05-30 06:12
hmmm, that should be the Qt GUI. What version of ROS are you using ?

**Comment by kubark42** [comment] 2014-05-30 11:44
I'm not sure if there's a way to give you a specific version, but it's Hydro that I installed two weeks ago.

**Comment by vrabaud** [comment] 2014-06-03 07:42
thx, do you know if that happened on Groovy too ?

**Comment by kubark42** [comment] 2014-06-03 12:32
I don't know, sorry. I only started using ROS a couple weeks ago and went right to Hydro.

**Comment by vrabaud** [comment] 2014-06-04 03:20
Hi, I actually switched image_pipeline to using OpenCV 2 features. It is here for now:
https://github.com/vrabaud/image_pipeline.git
(not in the official repo yet). Any chance it fixes your issue ?

**Comment by vrabaud** [comment] 2014-06-11 04:39
Hi, are you going to try Indigo anytime soon ? Indigo now uses cv2 purely which can only help (and I am wondering whether this will help your case).

**Comment by kubark42** [comment] 2014-06-13 02:39
@vrabaud The hydro install was pretty painful on OSX, so I'm not sure if I'll be successful at Indigo.

I tried the updated image_pipeline, but it failed to compile. (I can't put the bug report on your fork because for some reason there is no "issues" button there)

```
[ 85%] Built target stereo_view
/Users/kenz/Documents/catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyz.cpp:109:21: error: no viable
      overloaded '='
  cloud_msg->header = depth_msg->header;
  ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.7/pcl/PCLHeader.h:16:10: note: candidate function (the implicit copy assignment operator) not
      viable: no known conversion from 'const _header_type' (aka 'const Header_<std::__1::allocator<void> >') to
      'const pcl::PCLHeader' for 1st argument
  struct PCLHeader
         ^
/Users/kenz/Documents/catkin_ws/src/image_pipeline/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp:244:21: error: no
      viable overloaded '='
  cloud_msg->header = depth_msg->header; // Use depth image time stamp
  ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
/usr/local/include/pcl-1.7/pcl/PCLHeader.h:16:10: note: candidate function (the implicit copy assignment operator) not
      viable: no known conversion from 'const _header_type' (aka 'const Header_<std::__1::allocator<void> >') to
      'const pcl::PCLHeader' for 1st argument
  struct PCLHeader
         ^
1 warning generated.
1 error generated.
make[2]: *** [image_pipeline/depth_image_proc/CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyz.cpp.o] Error 1
1 warning and 1 error generated.
make[2]: *** [image_pipeline/depth_image_proc/CMakeFiles/depth_image_proc.dir/src/nodelets/point_cloud_xyzrgb.cpp.o] Error 1
make[1]: *** [image_pipeline/depth_image_proc/CMakeFiles/depth_image_proc.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed

~/Documents/catkin_ws$
```

**Comment by vrabaud** [comment] 2014-06-13 07:13
Right, you would need dependent packages from Indigo too sorry (you cannot use image_pipeline Indigo on Hydro).
If you can try full Indigo and you tell me it works, then I can try fixing Hydro (but this cv, cv2 change is painful so I won't do it until I'm sure it works).
OR
(actually simpler): just get camera_calibrator from Indigo, and leave the rest at Hydro. This is pure Python so it should work.

**Comment by kubark42** [comment] 2014-06-13 10:39
@vrabaud It's surprisingly difficult to find the sources for ROS (or maybe I'm failing at google this morning). Do you happen to have a direct link?

**Comment by vrabaud** [comment] 2014-06-13 14:35
For ? The whole indigo, follow the homebrew tutorials. FOr camera_calibrator, it's just:
https://github.com/ros-perception/image_pipeline/tree/indigo/camera_calibration

**Comment by kubark42** [comment] 2014-06-13 14:37
Thanks. By "camera_calibrator", I'm assuming you mean https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/src/camera_calibration/calibrator.py, right?

**Comment by vrabaud** [comment] 2014-06-13 16:02
actually, the whole folder (and the node files too). I changed the API all over in there.

**Comment by vrabaud** [comment] 2014-07-14 15:25
any news on that ? Thx

**Comment by vrabaud** [comment] 2014-08-03 13:40
how about the latest release, does that work for you ?

**Comment by vrabaud** [comment] 2014-09-06 20:29
@kubark42 , any news ?

**Comment by vrabaud** [comment] 2014-11-10 14:45
@kubark42 , any news ?

**Comment by vrabaud** [comment] 2015-02-15 14:24
@kubark42 , any news ?

**Comment by amarburg** [comment] 2015-02-20 05:33
I have this as well (or something quite like it).  Indigo built from source, Yosemite 10.10.2, Homebrew for most everything except system Python 2.7.6 and a self-compiled OpenCV 'master' (3.0.0-dev)

I get an appropriately sized window but it remains white ... nothing is ever drawn in it.  And a "beachball" cursor when it has focus.   No issues killing it from the command line.   

It appears to be calling imshow() in DisplayThread::run as its supposed to.  A few python demos from within the OpenCV3 tree also appear to be working (sorry, i don't normally work in Python so my ability to debug is limited).

**Comment by vrabaud** [comment] 2015-02-20 12:21
ok, how do you know it calls imshow in that thread ? Did you put a print before and after ?
Also, can you lease try increasing the waitKey to see if something does display eventually ? Thx.

**Comment by vrabaud** [comment] 2015-02-21 17:19
Do you have memory consumption that increases ? Basically, is it a duplicate of https://github.com/ros-perception/image_pipeline/issues/112 ?

**Comment by amarburg** [comment] 2015-02-21 17:51
Yes, I put prints before and after the call to imshow.

I will confirm that behavior and check the memory consumption.

**Comment by amarburg** [comment] 2015-02-23 17:45
I've just confirmed (using print before and after) that imshow is getting called.   The memory usage from the process is growing, but very slowly, so it does not appear to duplicate #112 .

I have switched to a lower-bandwidth video stream (downsampled and slower frame rate) and that does not improve things.  I will strip the .py back to a basic image viewer and see if i can identify if the problem lies in OpenCV, Python or the script itself.

**Comment by vrabaud** [comment] 2015-02-24 12:37
did you try augmenting the waitKey ? Can you please follow a basic Python OpenCV tutorial to see if you can display an image ?  like: http://docs.opencv.org/trunk/doc/py_tutorials/py_gui/py_image_display/py_image_display.html#py-display-image

**Comment by vrabaud** [comment] 2015-03-15 13:23
actually, which version of OpenCV are you using ? Make sure you have the latest in the 2.4 branch

**Comment by vrabaud** [comment] 2015-03-15 13:24
or if you're using OpenCV 3.0, make sure to update to the latest in the branch (rc should be out very soon).

**Comment by garciafa** [comment] 2015-10-01 10:10
I just found that openCV does not work on mac os x if called in a thread that is not the main thread.
I changed the init of OpenCVCalibrationNode to :
        self.queue_display = deque([], 1)
        self.display_thread = DisplayThread(self.queue_display, self)
        self.display_thread.run()

And all is working fine.

**Comment by JWhitleyWork** [comment] 2019-04-25 16:56
Closing very old thread due to lack of applicability to currently-supported ROS/OpenCV versions.

**Closed as completed by JWhitleyWork** 2019-04-25 16:56 UTC
