### ISSUE TITLE
memory grows unbounded during calibration

### ISSUE THREAD

**Issue by protobits** [ros-perception/image_pipeline#112] opened 2014-11-21 22:27 UTC
I have a problem where, during calibration, memory usage increases very fast. If I manage to avoid receiving a segmentation fault do to excessive memory usage, I see that after calibration process ends, the calibration window displays all past images captured during the calibration process. 

I've looked at the code and I've seen that images are queued and I think the queue has no limit. I wonder if this is the cause. If so, the queuing should be stopped before starting calibration to avoid this problem.

**Comment by vrabaud** [comment] 2014-11-22 09:42
This seems close to #97 , which version do you use ?

**Comment by protobits** [comment] 2014-11-22 14:06
I'm on 1.12.11.
Indeed it sounds like the same problem, however it looks it was not fixed.

**Comment by vrabaud** [comment] 2014-12-14 22:40
wait, so you don't see the images during calibration ? Only once done, are all the images that were used for calibration being displayed ? Under Python 2 ?

**Comment by protobits** [comment] 2014-12-14 22:58
It is python2, yes.
After I press calibrate, no, I don't see images anymore. The images appear
to be queued (without limits) until after the process finishes. Thus, when
it is done computing the calibration, it starts playing back everything
captured while it was calibrating.

**Comment by vrabaud** [comment] 2014-12-14 23:48
which OS ? Are you on GNOME or KDE ?

**Comment by protobits** [comment] 2014-12-15 00:08
KDE

**Comment by vrabaud** [comment] 2014-12-21 20:27
can you please try master ? Thx

**Comment by protobits** [comment] 2015-02-05 20:30
Hi,
it does not seem to change. I have to shutdown the camera node so that it
doesn't feeds images to the calibrator. Also, the calibrator does not
display images while calibrating (hence the queue going out of bounds).
I suspect a threading issue which does not allow consuming said queue.

**Comment by vrabaud** [comment] 2015-02-13 19:15
ok, could you please try to increase the value of 6ms to 10, 20 or 30 here:
https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/nodes/cameracalibrator.py#L75
If any of those work (to display things at least), please let me know.

**Comment by vrabaud** [comment] 2015-02-15 14:19
can you please give more info ? OS, camera. I really cannot reproduce that on 3 versions of Kubuntu ...
Do you have your own OpenCV by any chance ? Anything you compiled from source ?

**Comment by protobits** [comment] 2015-02-15 14:21
I'm on ArchLinux, have tried with pointgrey firefly mv cameras (using
camera1394 driver). I should not be using anything compiled by source. When
I tried latest version I did it on a separate clean catkin workspace.
I will try your suggestion sometime next week.

**Comment by vrabaud** [comment] 2015-02-15 14:24
which version of KDE ? I tried the latest 4 and 5.
It's just that the code should definitely display something: that stupid queue is being filled (that's why your memory increases), but somehow, it cannot display any image. You could simply put a print in that while loop I mentioned to see if it even gets there or pops out an image.

**Comment by protobits** [comment] 2015-02-15 14:25
Ok, I will try that as well at work, where I can try this.

I'll let you know any results.
Thanks!

**Comment by vrabaud** [comment] 2015-03-15 15:39
btw, do you have a custom version of OpenCV in /usr/local or somewhere else ?

**Comment by protobits** [comment] 2015-03-17 12:52
No, stock opencv from archlinux.

**Comment by bobbens** [comment] 2015-03-19 07:14
I'm seeing the same issue. From looking at the code it seems like it's basically the queue growing towards infinity. Best solution would be add a parameter that specifies how large the queue can grow before it just starts removing old images.

**Comment by vrabaud** [comment] 2015-03-23 09:24
can anybody please try master on indigo and let us know if that now works ? Thx

**Comment by vrabaud** [comment] 2015-03-29 13:25
ok, I'll asume it's fixed in master.

**Closed as completed by vrabaud** 2015-03-29 13:25 UTC
