### ISSUE TITLE
Issue rectifying 16bit mono images

### ISSUE THREAD

**Issue by LucidOne** [ros-perception/image_pipeline#55] opened 2014-02-20 19:52 UTC
```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.widt
h <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in
 Mat, file /tmp/buildd/ros-hydro-opencv2-2.4.6-3precise-20140130-1852/modules/co
re/src/matrix.cpp, line 323
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/buildd/ros-hydro-opencv2-2.4.6-3precise-20140130-1852/modules/co
re/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi
.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.row
s in function Mat
```

Launch File

```
  <group ns="/camera">
    <node pkg="nodelet" type="nodelet" name="rectify_mono"
      args="standalone image_proc/rectify" output="screen">
      <remap from="image_mono" to="image_raw" />
    </node>
  </group>
```

Here is the camera info
Image was decimated on-board the camera.

```
header: 
  seq: 9904
  stamp: 
    secs: 1392345058
    nsecs: 255573802
  frame_id: camera
height: 728
width: 968
distortion_model: plumb_bob
D: [-21.48163, 2154.22524, 0.24333000000000002, -0.24100000000000002, 0.0]
K: [6830.9773, 0.0, 437.66934, 0.0, 39782.98468, 304.66521, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [6439.25391, 0.0, 412.88838, 0.0, 0.0, 42096.67578, 324.95043, 0.0, 0.0, 0.0,
 1.0, 0.0]
binning_x: 2
binning_y: 2
roi: 
  x_offset: 0
  y_offset: 0
  height: 1456
  width: 1936
  do_rectify: True

---
```

Image header
rostopic echo --noarr /camera/image_raw

```
header: 
  seq: 9930
  stamp: 
    secs: 1392345061
    nsecs: 859107259
  frame_id: camera
height: 728
width: 968
encoding: mono16
is_bigendian: 0
step: 1936

---
```

**Comment by vrabaud** [comment] 2014-02-21 08:17
ok, it seems the error is because the ROI is bigger than the image size, and that's actually what the OpenCV error says. I guess that should be checked and an error should be logged.

**Comment by Lenskiy** [comment] 2014-03-13 08:30
I changed video format to Forma7 and reduced ROI in camera1394 config file, now whenever I run stereo image proc I get the same exceptions

```
artem:bags artemlenskiy$ ROS_NAMESPACE=stereo_sync rosrun stereo_image_proc stereo_image_proc

OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp, line 323
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp, line 323
libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
terminating with uncaught exception of type cv::Exception: /Users/artemlenskiy/ros/hydro/src/opencv2/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```

The resolution is not standard, these are my camera parameters 
binning_x: 1
binning_y: 1
roi_width:  1328 
roi_height: 600
y_offset: 128 
format7_color_coding: mono8
bayer_pattern: ""  

Looking for a solution now. Any ideas and directions are appreciated.

**Comment by Lenskiy** [comment] 2014-03-30 13:50
Sorry for the late reply. Generally the problem is in the way camera1394 package publishes camera_info. It adds non zero ROI parameters, however it publishes already cropped image. OpenCV tries to crop ROI from the already cropped image.
My temporary solution was to republish camera_info with ROI parameters set to zero.

**Comment by vrabaud** [comment] 2014-05-11 13:31
ok, so this hasm to be fixed upstream. Did you file a bug for 1394 ?

**Comment by Lenskiy** [comment] 2014-05-11 15:33
Just reposted the issue to 1394 package.

**Comment by vrabaud** [comment] 2014-05-11 16:12
thx, closing here: please, do not hesitate to re-open if it's indeed on the image_pipeline's side.

**Closed as completed by vrabaud** 2014-05-11 16:12 UTC
